### ISSUE TITLE
Pipe is broken.

### ISSUE THREAD

**Issue by hxbb00** [rosenbjerg/FFMpegCore#128]
```
                    var pipeSource = new StreamPipeSource(fs);
                    var arguments = await FFMpegArguments
                    .FromPipeInput(pipeSource)
                    .OutputToFile(outPath, true
                    , options => options
                    .ForceFormat("rawvideo")
                    .WithVideoCodec(VideoCodec.Png)
                     .WithFrameOutputCount(1))
                    .ProcessAsynchronously();
```

**Comment by hxbb00** [comment]
snapshot from pipe will throw exception ,but the png is output

**Comment by rosenbjerg** [comment]
Which version of the library are you version?

**Comment by hxbb00** [comment]
> Which version of the library are you version?

v3.1.0

**Comment by rosenbjerg** [comment]
Which exception is thrown? Do you have a stacktrace?

**Comment by hxbb00** [comment]
![image](https://user-images.githubusercontent.com/14104435/99019017-6bde8780-2596-11eb-8f6f-26c5650c1c75.png)

**Comment by hxbb00** [comment]
![image](https://user-images.githubusercontent.com/14104435/99019235-ddb6d100-2596-11eb-8314-c12cc91f7984.png)

**Comment by hxbb00** [comment]
`Writer.CopyAsync(Pipe, token)`
debug this code,the `Pipe ` is null, token cancelled,I guess it may be a thread synchronization problem

**Comment by rosenbjerg** [comment]
Thank you for images of the problem. You might be right that this is a thread synchronization problem. It seems like the process ends before the pipe connection is closed, and then cancels the pipe action.
And you say that the image is output correctly?

**Comment by hxbb00** [comment]
yes, the image is output correctly

**Comment by KarolStosik** [comment]
When result is also a pipe, getting output is impossible since the exception is thrown. Stack trace:

```
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFMpegCore.Arguments.InputPipeArgument.<ProcessDataAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFMpegCore.Arguments.PipeArgument.<During>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFMpegCore.FFMpegArguments.<During>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FFMpegCore.FFMpegArgumentProcessor.<ProcessAsynchronously>d__16.MoveNext()
```

**Comment by rosenbjerg** [comment]
Hi again, there have be a couple of fixes to the piping functionality in this libary. Could you try again with the latest version?

**Comment by KarolStosik** [comment]
There's another exception now:

Tested on FFMpegCore 4.1.0

```
ffmpeg version 4.3.1-2020-11-19-essentials_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000237eec2ea80] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 360x360, 275 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '\\.\pipe\FFMpegCore_e1c6771f-1cfd-49c7-8e9d-0e9b5d770871':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.25.101
  Duration: 00:00:10.01, start: 0.000000, bitrate: N/A
    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), none, 360x360, 275 kb/s, 30 fps, 30 tbr, 15360 tbn, 30720 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000237eec2ea80] stream 0, offset 0x2bfb6: partial file
\\.\pipe\FFMpegCore_e1c6771f-1cfd-49c7-8e9d-0e9b5d770871: Invalid data found when processing input
Cannot determine format of input stream 0:0 after EOF
Error marking filters as finished
Conversion failed!

   at FFMpegCore.FFMpegArgumentProcessor.HandleCompletion(Boolean throwOnError, Int32 exitCode, IReadOnlyList`1 errorData)
   at FFMpegCore.FFMpegArgumentProcessor.<ProcessAsynchronously>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```


My code (very similar to OP):
```
                    await FFMpegArguments
                    .FromPipeInput(new StreamPipeSource(inputStream), options => options
                        .Seek(time))
                    .OutputToPipe(new StreamPipeSink(ms), options => new Action<FFMpegArgumentOptions>(o => o
                        .WithVideoCodec(VideoCodec.Png)
                        .WithFrameOutputCount(1)
                        .ForceFormat("rawvideo"))(options))
                    .ProcessAsynchronously()
                    .ConfigureAwait(false);
```
  It works fine for Url input

**Comment by Toemsel** [comment]
Pipe is indeed broken
```

FFMpegCore.Exceptions.FFMpegException: 'ffmpeg exited with non-zero exit-code (1 - ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
\\.\pipe\FFMpegCore_74be1504-ffd2-492b-b0be-298158bfbf81: Invalid argument)'

```

Tried 3.3 - 4.2 ffmpeg versions. Lib version: 4.2

Edit: After debugging: You do require to pass a format as an argument. E.g.: 

`        public override string Text => $"-y -f avi {Writer.GetStreamArguments()} -i \"{PipePath}\"";`

works

Edit edit: works even without providing a format by removing the '-y' (override) param.

**Comment by Toemsel** [comment]
To be more clear, that '-y' needs to be removed from the code. I don't see why it is there in first place. You can add it as an optional argument for sure, but as it is now, it is always present and breaks the pipe.

**Comment by rosenbjerg** [comment]
@max619 Do you remember if there is a case where the `-y` is needed?

**Comment by Toemsel** [comment]
-y indicates to override the provided source. You can either set it manually or use the built-in override argument. But indeed good question why it is there

**Comment by rosenbjerg** [comment]
Yeah exactly. Maybe `-y` should only be added when outputting to a pipe, because then the pipe "file" will indeed exist. But I'm also thinking that removing it makes sense, but I want to hear @max619 if he remembers if there is a case where `-y` is actually necessary when using input from pipe

**Comment by Toemsel** [comment]
> Yeah exactly. Maybe `-y` should only be added when outputting to a pipe, because then the pipe "file" will indeed exist. But I'm also thinking that removing it makes sense, but I want to hear @max619 if he remembers if there is a case where `-y` is actually necessary when using input from pipe

Why would you need it for the pipe? The pipe is broken with -y as a prefix. Without -y it works just fine.

**Comment by max619** [comment]
@rosenbjerg actually i'm not really sure why -y (especially for input pipe) flag was used, if it works without it - fine.

But it's quite strange that some users experience issues with this flag but others don't.

**Comment by rosenbjerg** [comment]
@max619 Yeah that is quite strange, good point
@Toemsel If the unit tests still pass after I remove -y in InputPipe, I'll publish a new version

**Comment by rosenbjerg** [comment]
@Toemsel I have released version 4.3 in which -y is removed from InputPipeArgument. Could you try again

**Comment by rosenbjerg** [comment]
I'll close this issue now. Please reopen if the problem persists even after this fix

**Comment by spektor56** [comment]
I still have issue with "Pipe is broken" with the exact same code:

FFMpegArguments
                        .FromPipeInput(test)
                        .OutputToPipe(new StreamPipeSink(ms), options => options
                            .ForceFormat("rawvideo")
                            .WithVideoCodec(VideoCodec.Png)
                            .WithFrameOutputCount(1))
                        .ProcessSynchronously()

if i take out the WithFrameOutputCount(1) it's fine.  The code also works fine if i use FromFileInput instead of FromPipeInput

**Comment by kikutano** [comment]
@spektor56 did you find a solution for this problem? Probably I've the same: https://github.com/rosenbjerg/FFMpegCore/issues/263

**Comment by spektor56** [comment]
> @spektor56 did you find a solution for this problem? Probably I've the same: #263

Nope no solution yet

**Comment by kadia8161** [comment]
facing same issue please let us know if there is any update for this thread ..

**Comment by rosenbjerg** [comment]
@max619 Care to take a guess at why `WithFrameOutputCount(1)` would create the `Pipe is broken` problem? Maybe that ffmpeg feature requires seeking and that won't work with pipes?
