### ISSUE TITLE
randomly errors, "The process instance has already exited"

### ISSUE THREAD

**Issue by turkerdev** [rosenbjerg/FFMpegCore#348]
this error happens randomly, sometimes it works, sometimes it doesn't.

```
2022-07-19T15:22:59.903398863Z app[web.1]: Unhandled exception. Instances.Exceptions.InstanceProcessAlreadyExitedException: The process instance has already exited
2022-07-19T15:22:59.905210511Z app[web.1]:    at Instances.ProcessInstance.WaitForExit()
2022-07-19T15:22:59.905342235Z app[web.1]:    at Instances.Instance.Finish(ProcessStartInfo startInfo, EventHandler`1 outputHandler, EventHandler`1 errorHandler)
2022-07-19T15:22:59.905367732Z app[web.1]:    at Instances.Instance.Finish(String path, String arguments, EventHandler`1 outputHandler, EventHandler`1 errorHandler)
2022-07-19T15:22:59.905413878Z app[web.1]:    at FFMpegCore.Helpers.FFMpegHelper.VerifyFFMpegExists(FFOptions ffMpegOptions)
2022-07-19T15:22:59.905433033Z app[web.1]:    at FFMpegCore.FFMpegArgumentProcessor.PrepareProcessArguments(FFOptions ffOptions, CancellationTokenSource& cancellationTokenSource)
2022-07-19T15:22:59.905500853Z app[web.1]:    at FFMpegCore.FFMpegArgumentProcessor.ProcessAsynchronously(Boolean throwOnError, FFOptions ffMpegOptions)
```

**Comment by thienandangthanh** [comment]
I got the same error.

```
 Error Message:
   Instances.Exceptions.InstanceProcessAlreadyExitedException : The process instance has already exited
  Stack Trace:
     at Instances.ProcessInstance.WaitForExitAsync(CancellationToken cancellationToken)
   at FFMpegCore.ProcessArgumentsExtensions.StartAndWaitForExitAsync(ProcessArguments processArguments, CancellationToken cancellationToken)
   at FFMpegCore.FFProbe.AnalyseAsync(String filePath, FFOptions ffOptions, CancellationToken cancellationToken)
```

I only use FFProbe to get audio file duration.

``` cs
        var mediaInfo = await FFProbe.AnalyseAsync(tempPath);
        var fileDuration = (long)mediaInfo.Duration.TotalSeconds;
```

FFMpegCore version 4.8.0
ffmpeg version: 4.2.7
``` sh
ffmpeg -version

ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

**Comment by Nigrimmist** [comment]
Getting the same issue. 


```
FFMpegArguments
                   .FromFileInput(_filePath, verifyExists: false)
                   .OutputToFile(resultFilePath, overwrite: true, (FFMpegArgumentOptions options) =>
                   {
                       options.WithCustomArgument($"-i {backgroundFilePath} -filter_complex \"[0:v]scale = {resultSourceVideoWidth}x{resultSourceVideoHeight},setsar = 1[v0]; [1][v0] overlay = x = {imagePosX}:y = {imagePosY}\" -c:a copy -movflags +faststart");


                   }).NotifyOnOutput((string output) =>
                   {
                       Console.WriteLine(output);
                   })
                   .NotifyOnError((err) => { Console.WriteLine(err); })
                   .NotifyOnProgress((progress) =>
                   {
                       Console.WriteLine(progress);
                   }).ProcessSynchronously();
```

Instances.Exceptions.InstanceProcessAlreadyExitedException: The process instance has already exited
at Instances.ProcessInstance.WaitForExit()
at Instances.Instance.Finish(ProcessStartInfo startInfo, EventHandler`1 outputHandler, EventHandler`1 errorHandler)
at Instances.Instance.Finish(String path, String arguments, EventHandler`1 outputHandler, EventHandler`1 errorHandler) 
at FFMpegCore.Helpers.FFMpegHelper.VerifyFFMpegExists(FFOptions ffMpegOptions)
at FFMpegCore.FFMpegArgumentProcessor.PrepareProcessArguments(FFOptions ffOptions, CancellationTokenSource& cancellationTokenSour...

ffmpeg-5.0.1-amd64
ffMpegCore 4.8

Looks like if try to do it few times in a row - work fine, but in general it is not a good solution, fix required. Thanks

**Comment by pirahtays** [comment]
I am having the same issue on a Mac Studio, Arm64 code.  No new info other than that.  I can provide code if needed.  Resolved this by using version Nuget package 4.7.0

**Comment by thienandangthanh** [comment]
Thank you, @pirahtays, for your info.
I downgraded FFMpegCore from [4.8.0](https://www.nuget.org/packages/FFMpegCore/4.8.0#release-body-tab) to [4.7.0](https://www.nuget.org/packages/FFMpegCore/4.7.0). And it works without any error.

The problem maybe from the feature "CancellationToken support for `AnalyseAsync`" of version 4.8.0 https://github.com/rosenbjerg/FFMpegCore/issues/299?

**Comment by rosenbjerg** [comment]
Version 5.0.0 which should fix this issue has been released, please reopen if that is not the case

**Comment by suprak** [comment]
Still seeing this on `5.2.0`.

Mind you the await below is in a try/catch and this randomly still evades it.

Using this code,
```c#
await FFMpegArguments
        .FromUrlInput(url)
        .OutputToPipe(new StreamPipeSink(stream), _ =>
        {
            _.WithVideoCodec("mjpeg")
             .WithFrameOutputCount(1)
             .ForceFormat("image2")
             .WithCustomArgument("-vf \"scale=1024:-1\"")
             .WithFastStart();
        })
        .CancellableThrough(cancellationToken)
        .ProcessAsynchronously();
```

```
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (The process instance has already exited))
 ---> System.AggregateException: One or more errors occurred. (The process instance has already exited)
 ---> Instances.Exceptions.InstanceProcessAlreadyExitedException: The process instance has already exited
   at Instances.ProcessInstance.ThrowIfProcessExited()
   at Instances.ProcessInstance.SendInput(String input)
   at FFMpegCore.FFMpegArgumentProcessor.<>c__DisplayClass25_0.<Process>g__OnCancelEvent|0(Object sender, Int32 timeout)
   at FFMpegCore.FFMpegArgumentProcessor.<>c__DisplayClass20_0.<CancellableThrough>b__0()
   at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by snechaev** [comment]
Yes, there is still a race condition here in line 169 (`SendInput()` call)

https://github.com/rosenbjerg/FFMpegCore/blob/a599c48511cb9ba059b00e3c3a4276650388ec4b/FFMpegCore/FFMpeg/FFMpegArgumentProcessor.cs#L167-L174

At the moment when cancellation was initiated by the caller, the underlying process can be already exited and the `SendInput()` will throw `InstanceProcessAlreadyExitedException`.

In this particular case, it looks like we can safely ignore this exception, e.g. add the `try/catch` clause in the `OnCancelEvent()`.

P.S. By the way, the same exception will be thrown on the `instance.Kill()` call, so it should be also handled or explicitly ignored.

@rosenbjerg It appears that I don't have the necessary permissions to reopen this issue. Could you please reopen it yourself?
