### ISSUE TITLE
Frames colors get lost on output

### ISSUE THREAD

**Issue by amunim** [rosenbjerg/FFMpegCore#58]
[Example Project](https://we.tl/t-YumNCI8CQz), If I use `BitmapVideoFrameWrapper` to wrap around my Bitmap Frames and store ~65 Frames i.e. 2 seconds of footage and output to MP4 (to test if the output is correct before directly getting bytes of it) the colors shifts towards blue-ish tint and the output is not great.  think this is a bug in `BitmapVideoFrameWrapper` but moderators can find out the real cause

**Comment by rosenbjerg** [comment]
It would be much easier if you put the example project on GitHub, so it can be browsed without downloading files from external files. Would that be possible? But your problem sounds like something that could be related to the pixel format of the BitmapVideoFrameWrapper. What is the pixel format of the incoming frames?

**Comment by max619** [comment]
I think, for some reason, [Here](https://github.com/rosenbjerg/FFMpegCore/blob/b8fc8e574226e93b45e47d0f62845c684513b611/FFMpegCore/Extend/BitmapVideoFrameWrapper.cs#L73) we should use `bgr24` instead of `rgb24`, because [here](https://github.com/rosenbjerg/FFMpegCore/blob/b8fc8e574226e93b45e47d0f62845c684513b611/FFMpegCore/Extend/BitmapVideoFrameWrapper.cs#L75) i had to change `argb` to `rgba` too

**Comment by amunim** [comment]
Pixel format for the receiving bitmaps is `Pixel format: Format24bppRgb`, I hope it helps :)

**Comment by rosenbjerg** [comment]
I have just merged fixes for this from @max619, it will be included in next version, which will be 2.0.0

**Comment by rosenbjerg** [comment]
Version 2.0.0 has been released. This includes the pixel format fix by Max

**Comment by amunim** [comment]
@rosenbjerg hate it to break it to you but it is still not fixed.
![image](https://user-images.githubusercontent.com/24316328/107041527-72ba1680-67e2-11eb-9dfb-e50704ac67e1.png)
these are 69 image samples from the webcam and as you can see there are no problems with the frames, I used `bitmap.Save()` method to save the memoryBMP images.

Now, to get .mp4 output
      
     `RawVideoPipeSource _rawVideo = new RawVideoPipeSource(_notEncodedFrames.GetConsumingEnumerable().ToList())
                {
                    FrameRate = 20
                };
                await FFMpegArguments
                        .FromPipeInput(_rawVideo)
                        .OutputToFile("Temporary.mp4", true, options =>
                            options
                            .WithFastStart())
                        .NotifyOnProgress((progress) => Debug.WriteLine("Encode Progress: {0}", progress))
                        .ProcessAsynchronously();`
      

this produces video like this: 
![Capture](https://user-images.githubusercontent.com/24316328/107043415-ccbbdb80-67e4-11eb-9738-e853c9053a31.PNG)

**NOTE: this video is not playable in windows 10 player, I am using QQ player to watch the video**
Another interesting thing I observed is hovering mouse over the timeline seeks the correct frame which has no errors as you can see in the picture and this color issues arise only when playing the video.

Now, for .webm output
     
     ```RawVideoPipeSource _rawVideo = new RawVideoPipeSource(_notEncodedFrames.GetConsumingEnumerable().ToList())
                {
                    FrameRate = 20
                };
                await FFMpegArguments
                        .FromPipeInput(_rawVideo)
                        .OutputToFile("Temporary.webm", true, options =>
                            options
                            .WithFastStart())
                        .NotifyOnProgress((progress) => Debug.WriteLine("Encode Progress: {0}", progress))
                        .ProcessAsynchronously();```
     
~~_this increases the encoding time, so for 2 seconds of footage more than 12 seconds are wasted and file size is even larger than .mp4_, although this is not the scope of the question I'll be happy to get the answer for this :)~~(that's because of vp9 encoding apparently)

output: 
![image](https://user-images.githubusercontent.com/24316328/107042890-0f30e880-67e4-11eb-97cb-64c7081be516.png)
